version: '3.5'

services:
        mysql:
                image: mysql:5.6
                ports:
                        - '3306:3306'
                volumes:
                        - ./db-volume:/var/lib/mysql
                        - ./database.sql:/docker-entrypoint-initdb.d/database.sql
                        - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
                environment:
                        - MYSQL_DATABASE=ctf
                        - MYSQL_ROOT_PASSWORD=5M4AkmuTJ
                networks:
                        - dev-local
        web:
                build: .
                depends_on:
                        - mysql
                ports:
                        - '80:80'
                stdin_open: true
                tty: true
                volumes:
                        - ./source:/var/www/html
                        - ./logs:/var/log/apache2
                networks:
                        - dev-local        
networks:
        dev-local:
                driver: bridge
                name: dev-local
